[package]
name = "rust-ble-mesh"
version = "0.1.0"
authors = ["Mattia Fiumara <mattiafiumara@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
