name: Rust

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    
    strategy:
      matrix:
        channel: [stable, beta, nightly]
        # os: [ubuntu-latest, windows-latest, macOS-latest]
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: rustup install ${{ matrix.channel }} && rustup component add clippy rustfmt
    - name: Lint
      run: rustfmt && cargo fmt && cargo clippy
    - name: Build
      run: cargo +${{ matrix.channel }} build --verbose
    - name: Run tests
      run: cargo +${{ matrix.channel }} test --verbose
