name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        channel: [stable, beta, nightly]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: rustup component add clippy rustfmt
    - name: Lint
      run: rustfmt && cargo fmt && cargo clippy
    - name: Build
      run: cargo +${{ matrix.os }} build --verbose
    - name: Run tests
      run: cargo +${{ matrix.os }} test --verbose
